import { useState, useCallback } from 'react';
import { QualityMetrics } from '@/components/onboarding/quality-score-dashboard';
import { MissingInformation } from '@/components/onboarding/missing-information-alerts';
import { Recommendation } from '@/components/onboarding/quality-recommendations';
import { QualityReport } from '@/components/onboarding/quality-report-generator';

interface QualityAssuranceData {
  qualityMetrics: QualityMetrics;
  missingInformation: MissingInformation[];
  recommendations: Recommendation[];
}

interface UseQualityAssuranceOptions {
  hotelId: string;
  apiBaseUrl?: string;
}

export function useQualityAssurance({ hotelId, apiBaseUrl = '/api' }: UseQualityAssuranceOptions) {
  const [data, setData] = useState<QualityAssuranceData | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchDashboardData = useCallback(async (): Promise<QualityAssuranceData> => {
    setIsLoading(true);
    setError(null);

    try {
      const response = await fetch(`${apiBaseUrl}/hotels/${hotelId}/quality/dashboard-data`);
      
      if (!response.ok) {
        throw new Error(`Failed to fetch quality data: ${response.statusText}`);
      }

      const dashboardData = await response.json();
      setData(dashboardData);
      return dashboardData;
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to fetch quality data';
      setError(errorMessage);
      throw err;
    } finally {
      setIsLoading(false);
    }
  }, [hotelId, apiBaseUrl]);

  const generateReport = useCallback(async (reportHotelId: string): Promise<QualityReport> => {
    try {
      const response = await fetch(`${apiBaseUrl}/hotels/${reportHotelId}/quality/report`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (!response.ok) {
        throw new Error(`Failed to generate report: ${response.statusText}`);
      }

      return await response.json();
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to generate report';
      throw new Error(errorMessage);
    }
  }, [apiBaseUrl]);

  const downloadReport = useCallback((report: QualityReport) => {
    // Create a comprehensive report document
    const reportContent = `
QUALITY ASSURANCE REPORT
========================

Property: ${report.enhancedHotelId}
Generated: ${new Date(report.createdAt).toLocaleString()}
Generated By: ${report.generatedBy}

OVERALL SCORES
--------------
Overall Score: ${report.overallScore}%
Image Quality: ${report.imageQualityScore}%
Content Completeness: ${report.contentCompletenessScore}%
Policy Clarity: ${report.policyClarityScore}%

MISSING INFORMATION
-------------------
${report.missingInformation.map(missing => 
  `${missing.category} (${missing.priority} priority):\n${missing.items.map(item => `  - ${item}`).join('\n')}`
).join('\n\n')}

RECOMMENDATIONS
---------------
${report.recommendations.map((rec, index) => 
  `${index + 1}. ${rec.title} (${rec.priority} priority, +${rec.estimatedImpact} pts)
   ${rec.description}
   Action: ${rec.actionRequired}`
).join('\n\n')}

Report ID: ${report.id}
    `.trim();

    // Create and download the file
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `quality-report-${report.enhancedHotelId}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }, []);

  const shareReport = useCallback(async (report: QualityReport) => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Quality Assurance Report',
          text: `Quality report for property ${report.enhancedHotelId} - Overall Score: ${report.overallScore}%`,
          url: window.location.href,
        });
      } catch (err) {
        console.log('Error sharing report:', err);
        // Fallback to copying to clipboard
        fallbackShare(report);
      }
    } else {
      fallbackShare(report);
    }
  }, []);

  const fallbackShare = (report: QualityReport) => {
    const shareText = `Quality Report - Overall Score: ${report.overallScore}%\nGenerated: ${new Date(report.createdAt).toLocaleString()}`;
    
    if (navigator.clipboard) {
      navigator.clipboard.writeText(shareText).then(() => {
        alert('Report summary copied to clipboard!');
      }).catch(() => {
        alert('Unable to copy to clipboard');
      });
    } else {
      alert('Sharing not supported on this device');
    }
  };

  return {
    data,
    isLoading,
    error,
    fetchDashboardData,
    generateReport,
    downloadReport,
    shareReport,
  };
}