/**
 * Step Configurations
 * Defines all step configurations for the unified component
 */

import { StepConfigMap } from '../types/step-config';
import {
  basicDetailsSchema,
  locationSchema,
  amenitiesSchema,
  imagesSchema,
  roomsSchema,
  policiesSchema,
  businessFeaturesSchema,
  reviewSchema,
} from '../validation/schemas';

export const stepConfigs: StepConfigMap = {
  'basic-details': {
    id: 'basic-details',
    title: 'Basic Details',
    description: 'Tell us about your property',
    estimatedTime: 3,
    completionHint: 'Provide your property name, type, and description',
    validation: basicDetailsSchema,
    fields: [
      {
        name: 'name',
        type: 'text',
        label: 'Property Name',
        placeholder: 'Enter your property name',
        required: true,
        description: 'The name guests will see when booking',
      },
      {
        name: 'hotelType',
        type: 'select',
        label: 'Property Type',
        required: true,
        options: [
          { value: 'HOTEL', label: 'Hotel', description: 'Traditional hotel with multiple rooms' },
          { value: 'RESORT', label: 'Resort', description: 'Full-service resort with amenities' },
          { value: 'GUESTHOUSE', label: 'Guest House', description: 'Small, family-run accommodation' },
          { value: 'HOMESTAY', label: 'Homestay', description: 'Stay with local families' },
          { value: 'APARTMENT', label: 'Apartment', description: 'Self-contained apartment units' },
        ],
      },
      {
        name: 'description',
        type: 'textarea',
        label: 'Description',
        placeholder: 'Describe your property (optional)',
        rows: 4,
        description: 'Help guests understand what makes your property special',
      },
    ],
  },

  'location': {
    id: 'location',
    title: 'Location Details',
    description: 'Where is your property located?',
    estimatedTime: 5,
    completionHint: 'Provide complete address and contact information',
    validation: locationSchema,
    sections: [
      {
        title: 'Address Information',
        description: 'Provide your property\'s complete address',
        fields: ['address', 'city', 'state', 'pincode'],
      },
      {
        title: 'Contact Information',
        description: 'How can guests reach you?',
        fields: ['phone', 'email', 'website'],
      },
    ],
    fields: [
      {
        name: 'address',
        type: 'textarea',
        label: 'Street Address',
        placeholder: 'Enter complete street address',
        required: true,
        rows: 3,
      },
      {
        name: 'city',
        type: 'text',
        label: 'City',
        placeholder: 'Enter city name',
        required: true,
      },
      {
        name: 'state',
        type: 'text',
        label: 'State',
        placeholder: 'Enter state name',
        required: true,
      },
      {
        name: 'pincode',
        type: 'text',
        label: 'Pincode',
        placeholder: 'Enter 6-digit pincode',
        required: true,
        validation: {
          pattern: /^[1-9][0-9]{5}$/,
          message: 'Enter a valid 6-digit pincode',
        },
      },
      {
        name: 'phone',
        type: 'text',
        label: 'Phone Number',
        placeholder: '+91 9999999999',
        required: true,
        description: 'Primary contact number for guests',
      },
      {
        name: 'email',
        type: 'text',
        label: 'Email Address',
        placeholder: 'contact@yourproperty.com',
        description: 'Optional email for guest communication',
      },
      {
        name: 'website',
        type: 'text',
        label: 'Website',
        placeholder: 'https://yourproperty.com',
        description: 'Your property website (optional)',
      },
    ],
  },

  'amenities': {
    id: 'amenities',
    title: 'Amenities & Services',
    description: 'What amenities do you offer?',
    estimatedTime: 4,
    completionHint: 'Select all amenities and services available at your property',
    validation: amenitiesSchema,
    fields: [
      {
        name: 'amenities',
        type: 'multiselect',
        label: 'Property Amenities',
        required: true,
        description: 'Select all amenities available at your property',
        options: [
          { value: 'wifi', label: 'Free WiFi' },
          { value: 'parking', label: 'Free Parking' },
          { value: 'ac', label: 'Air Conditioning' },
          { value: 'restaurant', label: 'Restaurant' },
          { value: 'pool', label: 'Swimming Pool' },
          { value: 'gym', label: 'Fitness Center' },
          { value: 'spa', label: 'Spa Services' },
          { value: 'laundry', label: 'Laundry Service' },
          { value: 'room-service', label: '24/7 Room Service' },
          { value: 'concierge', label: 'Concierge Service' },
          { value: 'business-center', label: 'Business Center' },
          { value: 'conference-room', label: 'Conference Rooms' },
          { value: 'elevator', label: 'Elevator' },
          { value: 'wheelchair-accessible', label: 'Wheelchair Accessible' },
          { value: 'pet-friendly', label: 'Pet Friendly' },
        ],
      },
      {
        name: 'services',
        type: 'multiselect',
        label: 'Additional Services',
        description: 'Optional services you provide',
        options: [
          { value: 'airport-shuttle', label: 'Airport Shuttle' },
          { value: 'car-rental', label: 'Car Rental' },
          { value: 'tour-booking', label: 'Tour Booking' },
          { value: 'currency-exchange', label: 'Currency Exchange' },
          { value: 'babysitting', label: 'Babysitting Service' },
          { value: 'dry-cleaning', label: 'Dry Cleaning' },
          { value: 'wake-up-service', label: 'Wake-up Service' },
          { value: 'luggage-storage', label: 'Luggage Storage' },
        ],
      },
    ],
  },

  'images': {
    id: 'images',
    title: 'Property Images',
    description: 'Upload photos of your property',
    estimatedTime: 10,
    completionHint: 'Upload at least 3 high-quality images',
    validation: imagesSchema,
    fields: [
      {
        name: 'images',
        type: 'array',
        label: 'Property Images',
        required: true,
        description: 'Upload high-quality images that showcase your property',
        arrayConfig: {
          addButtonText: 'Add Image',
          removeButtonText: 'Remove',
          minItems: 3,
          maxItems: 20,
          itemFields: [
            {
              name: 'url',
              type: 'text',
              label: 'Image URL',
              required: true,
            },
            {
              name: 'type',
              type: 'select',
              label: 'Image Type',
              required: true,
              options: [
                { value: 'EXTERIOR', label: 'Exterior View' },
                { value: 'LOBBY', label: 'Lobby/Reception' },
                { value: 'ROOM', label: 'Guest Room' },
                { value: 'AMENITY', label: 'Amenity/Facility' },
                { value: 'OTHER', label: 'Other' },
              ],
            },
            {
              name: 'caption',
              type: 'text',
              label: 'Caption',
              placeholder: 'Brief description of the image',
            },
          ],
        },
      },
    ],
  },

  'rooms': {
    id: 'rooms',
    title: 'Room Configuration',
    description: 'Set up your room types and pricing',
    estimatedTime: 8,
    completionHint: 'Add all your room types with pricing and details',
    validation: roomsSchema,
    fields: [
      {
        name: 'rooms',
        type: 'array',
        label: 'Room Types',
        required: true,
        description: 'Configure all your room types',
        arrayConfig: {
          addButtonText: 'Add Room Type',
          removeButtonText: 'Remove Room',
          minItems: 1,
          maxItems: 10,
          itemFields: [
            {
              name: 'name',
              type: 'text',
              label: 'Room Name',
              placeholder: 'e.g., Deluxe Double Room',
              required: true,
            },
            {
              name: 'type',
              type: 'select',
              label: 'Room Type',
              required: true,
              options: [
                { value: 'SINGLE', label: 'Single Room' },
                { value: 'DOUBLE', label: 'Double Room' },
                { value: 'SUITE', label: 'Suite' },
                { value: 'FAMILY', label: 'Family Room' },
                { value: 'DORMITORY', label: 'Dormitory' },
              ],
            },
            {
              name: 'capacity',
              type: 'number',
              label: 'Guest Capacity',
              required: true,
              min: 1,
              max: 20,
              description: 'Maximum number of guests',
            },
            {
              name: 'basePrice',
              type: 'number',
              label: 'Base Price',
              required: true,
              min: 100,
              max: 100000,
              prefix: '₹',
              description: 'Price per night (weekday)',
            },
            {
              name: 'maxOccupancy',
              type: 'number',
              label: 'Maximum Occupancy',
              min: 1,
              max: 20,
              description: 'Maximum guests including extra beds',
            },
            {
              name: 'bedCount',
              type: 'number',
              label: 'Number of Beds',
              min: 1,
              max: 10,
            },
            {
              name: 'bedType',
              type: 'text',
              label: 'Bed Type',
              placeholder: 'e.g., King Size, Twin Beds',
            },
            {
              name: 'roomSize',
              type: 'number',
              label: 'Room Size',
              min: 50,
              suffix: 'sq ft',
              description: 'Room area in square feet',
            },
            {
              name: 'weekendPrice',
              type: 'number',
              label: 'Weekend Price',
              min: 100,
              prefix: '₹',
              description: 'Weekend/holiday pricing (optional)',
            },
          ],
        },
      },
    ],
  },

  'policies': {
    id: 'policies',
    title: 'Property Policies',
    description: 'Set your check-in/out times and policies',
    estimatedTime: 5,
    completionHint: 'Define your property policies and timings',
    validation: policiesSchema,
    sections: [
      {
        title: 'Check-in & Check-out',
        fields: ['checkIn', 'checkOut'],
      },
      {
        title: 'Property Policies',
        fields: ['cancellationPolicy', 'childPolicy', 'petPolicy', 'smokingPolicy'],
      },
    ],
    fields: [
      {
        name: 'checkIn',
        type: 'time',
        label: 'Check-in Time',
        required: true,
        description: 'Standard check-in time (24-hour format)',
      },
      {
        name: 'checkOut',
        type: 'time',
        label: 'Check-out Time',
        required: true,
        description: 'Standard check-out time (24-hour format)',
      },
      {
        name: 'cancellationPolicy',
        type: 'select',
        label: 'Cancellation Policy',
        required: true,
        options: [
          { 
            value: 'FLEXIBLE', 
            label: 'Flexible', 
            description: 'Free cancellation until 24 hours before check-in' 
          },
          { 
            value: 'MODERATE', 
            label: 'Moderate', 
            description: 'Free cancellation until 48 hours before check-in' 
          },
          { 
            value: 'STRICT', 
            label: 'Strict', 
            description: 'Free cancellation until 7 days before check-in' 
          },
        ],
      },
      {
        name: 'childPolicy',
        type: 'textarea',
        label: 'Child Policy',
        placeholder: 'Describe your policy for children (age limits, extra charges, etc.)',
        required: true,
        rows: 3,
      },
      {
        name: 'petPolicy',
        type: 'select',
        label: 'Pet Policy',
        required: true,
        options: [
          { value: 'ALLOWED', label: 'Pets Allowed' },
          { value: 'NOT_ALLOWED', label: 'No Pets' },
          { value: 'ON_REQUEST', label: 'Pets on Request' },
        ],
      },
      {
        name: 'smokingPolicy',
        type: 'select',
        label: 'Smoking Policy',
        required: true,
        options: [
          { value: 'ALLOWED', label: 'Smoking Allowed' },
          { value: 'NOT_ALLOWED', label: 'No Smoking' },
          { value: 'DESIGNATED_AREAS', label: 'Designated Smoking Areas' },
        ],
      },
    ],
  },

  'business-features': {
    id: 'business-features',
    title: 'Business Features',
    description: 'Configure booking and payment options',
    estimatedTime: 4,
    completionHint: 'Set up your booking preferences and payment methods',
    validation: businessFeaturesSchema,
    sections: [
      {
        title: 'Booking Settings',
        fields: ['instantBooking'],
      },
      {
        title: 'Payment & Communication',
        fields: ['paymentMethods', 'languages'],
      },
    ],
    fields: [
      {
        name: 'instantBooking',
        type: 'checkbox',
        label: 'Enable Instant Booking',
        description: 'Allow guests to book immediately without approval',
      },
      {
        name: 'paymentMethods',
        type: 'multiselect',
        label: 'Payment Methods',
        required: true,
        description: 'Select all payment methods you accept',
        options: [
          { value: 'cash', label: 'Cash' },
          { value: 'card', label: 'Credit/Debit Card' },
          { value: 'upi', label: 'UPI' },
          { value: 'netbanking', label: 'Net Banking' },
          { value: 'wallet', label: 'Digital Wallet' },
          { value: 'bank-transfer', label: 'Bank Transfer' },
        ],
      },
      {
        name: 'languages',
        type: 'multiselect',
        label: 'Languages Spoken',
        required: true,
        description: 'Languages your staff can communicate in',
        options: [
          { value: 'english', label: 'English' },
          { value: 'hindi', label: 'Hindi' },
          { value: 'bengali', label: 'Bengali' },
          { value: 'tamil', label: 'Tamil' },
          { value: 'telugu', label: 'Telugu' },
          { value: 'marathi', label: 'Marathi' },
          { value: 'gujarati', label: 'Gujarati' },
          { value: 'kannada', label: 'Kannada' },
          { value: 'malayalam', label: 'Malayalam' },
          { value: 'punjabi', label: 'Punjabi' },
          { value: 'urdu', label: 'Urdu' },
          { value: 'other', label: 'Other' },
        ],
      },
    ],
  },

  'review': {
    id: 'review',
    title: 'Review & Submit',
    description: 'Review your information and complete setup',
    estimatedTime: 3,
    completionHint: 'Review all details and agree to terms',
    validation: reviewSchema,
    fields: [
      {
        name: 'agreedToTerms',
        type: 'checkbox',
        label: 'I agree to the Terms of Service and Privacy Policy',
        required: true,
        description: 'You must agree to our terms to complete the setup',
      },
    ],
  },
};